/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'primary-container': '#064E3B',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#6e372f',
        'on-error-container': '#93000a',
        'inverse-primary': '#95d3ba',
        'surface-bright': '#f8faf9',
        'inverse-surface': '#2e3131',
        'surface-container-high': '#e6e9e8',
        'tertiary': '#4f1f19',
        'error': '#ba1a1a',
        'on-background': '#191c1c',
        'on-primary-fixed-variant': '#0b513d',
        'on-primary-fixed': '#002117',
        'on-surface-variant': '#404944',
        'secondary': '#1b6b4f',
        'surface-container-low': '#f2f4f3',
        'surface-container': '#eceeed',
        'secondary-container': '#a6f2cf',
        'on-tertiary-fixed': '#380d08',
        'outline': '#707974',
        'background': '#f8faf9',
        'on-tertiary': '#ffffff',
        'tertiary-fixed-dim': '#ffb4a9',
        'primary-fixed': '#b0f0d6',
        'surface': '#f8faf9',
        'on-secondary-fixed-variant': '#00513a',
        'on-tertiary-container': '#ea9e93',
        'primary-fixed-dim': '#95d3ba',
        'on-primary-container': '#80bea6',
        'on-secondary-fixed': '#002115',
        'surface-variant': '#e1e3e2',
        'on-primary': '#ffffff',
        'surface-tint': '#2b6954',
        'secondary-fixed-dim': '#8bd6b4',
        'primary': '#003527',
        'inverse-on-surface': '#eff1f0',
        'secondary-fixed': '#a6f2cf',
        'surface-container-lowest': '#ffffff',
        'outline-variant': '#bfc9c3',
        'on-secondary-container': '#247155',
        'tertiary-container': '#6b342d',
        'tertiary-fixed': '#ffdad5',
        'on-secondary': '#ffffff',
        'on-surface': '#191c1c',
        'surface-dim': '#d8dada',
        'surface-container-highest': '#e1e3e2',
      },
      borderRadius: {
        'lg': '1rem',
        'xl': '1.5rem',
        '2xl': '2rem',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        headline: ['Plus Jakarta Sans', 'sans-serif'],
        body: ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0px 20px 40px rgba(0, 33, 23, 0.06)',
        'tonal': '0 4px 30px rgba(0, 33, 23, 0.03)',
        'glass': '0 8px 32px rgba(0, 33, 23, 0.08)',
      },
      backdropBlur: {
        'glass': '20px',
      },
    },
  },
  plugins: [],
}
